source "https://rubygems.org"

gem 'pry-byebug'
gem 'word-salad', '~> 1.0'
gem 'sqlite3'
gem 'random-word-generator', '~> 0.0.1'
gem 'random-word', '~> 1.3'
gem 'require_all'
gem 'sinatra'
gem 'tux'
gem 'rake'
gem 'thin'
gem 'shotgun'
gem 'activerecord'
gem 'sinatra-activerecord'
